networks:
  sentinel-network:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:

services:
  sentinel-agent:
    build:
      context: .
      args:
        VERSION: "2.0.0"
        COMMIT: "a73f18f"
        DATE: "2026-07-18"
    image: sentinel-agent:v2.0
    container_name: sentinel_agent
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - ./secrets/.env
    environment:
      - TZ=Europe/Madrid
      - SENTINEL_SOCKET_PATH=/run/sentinel/sentinel.sock
    networks:
      - sentinel-network
    volumes:
      - /run/sentinel:/run/sentinel
    tmpfs:
      - /tmp:size=4M
    ports:
      - "2112:2112"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:2112/healthz"]
      interval: 15s
      timeout: 3s
      retries: 3
    restart: unless-stopped


  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: sentinel_prometheus
    networks:
      - sentinel-network
    expose:
      - "9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.4.1
    container_name: sentinel_grafana
    networks:
      - sentinel-network
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped
